# -*- coding: utf-8 -*-
"""desafio-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1khvfnC8v-WRC5BsbI9I1mD_Y2l2f4Ccm

# Desafio-1

Olá Mundo

$$  f(x) = e^x = \sum_{n=1}^{\infty}\frac{x^x}{n!}  $$
$$  g(x) = \int f(x)dx  $$
$$  m\ddot{x} = \frac{x}{2} $$

Olá, mundo
Por definição, esta é a formula da puta que o pariu: $$f(x) = e^x = \sum_{n=1}^{\infty}\frac{x^x}{n!}$$

## Relatório final

Vou colocar o meu relatório final no início para facilitar a leitura, já que acredito que o meu programa ficou maior que o esperado.

Perfis encontrados

Com base na análise bivariada entre variáveis demográficas e o resultado do questionário DPQ. Foi possível elaborar um perfil com maior incidência de sintomas de depressão: sexo feminino, entre 50 e 59 anos, negra não-hispânica, que estudou até o 12° ano e que possui renda entre 5000 e 9999 dólares.

O perfil que possui maior adequação a uma alimentação saudável é o de uma pessoa do sexo feminino, branca, com mais de 70 anos, com renda entre US$45000 e US$54999 anuais ou maior que US$75000, e que estudou até o 9 ano ou possui ensino superior completo.

O perfil com maior aderência à atividades físicas é o de uma pessoa do sexo masculino, negra ou 'outra-hispânica', entre 18 e 19 anos com renda de até US$4999 anuais.

Acredito que o tipo de estudo empregado pela Nhanes seja do tipo observacional, uma vez que não houve interveção do pesquisador na manipulação das variáveis para posteriormente comparar com um grupo de controle.

Na análise realizada por mim existem algumas fontes de viés: eu não fiz uma limpeza nos outliers primeiro por entender que ao remover alguns outliers, por exemplo no escore do questionário DPQ, eu perderia dados bastante relevantes. Felizmente a depressão não atinge grande parte da população, e ao remover pontuações altas no questionário, eu estaria removendo eventos relevantes para a minha análise e eu acredito que esses dados enviesaram sim minha análise em alguma escala.

O segundo motivo para a não-limpeza nos valores extremos se deu pelo fato de eu não compreender ainda de fato o quanto isso interfere na minha análise, portanto pretendo estudar melhor sobre EDA e retornar a esse dataset em um futuro próximo.

Outro fator que provavelmente enviesou minha análise, foi a maior quantidade de mulheres em relação a homens, mas voltamos ao problema do escore do questionário: mulheres tiveram pontuações maiores que os homens, talvez, se eu tivesse tirado alguns desses eventos, eu não teria como saber isso.

No dataset em si, eu acredito que o volume de pessoas bastante jovens também possa ter enviesado a análise, mas é compreensível, devido à amostragem complexa da pesquisa.

Durante a minha análise, eu determinei que variáveis que possuíssem coeficientes de correlação maiores ou iguais a 0,1 e menores ou iguais a -0,1 seriam considerados relevantes. Dentre as variáveis que servem como indicador de hábitos saudáveis, apenas a que mede a aderência a atividades físicas teve alguma relação com os sintomas de depressão.

As variáveis que, aparentemente, mais influenciaram a pontuação no questionário DPQ foram sexo e renda familiar anual. Claro que essas também variáveis tem relação com outra variáveis.

Um problema, identificado agora, ao escrever esse relatório, e que pretendo resolver na próxima visita a esse dataset é o fato de que o perfil encontrado às vezes não existe na minha análise. Exemplo: um jovem de 19 anos com ensino superior completo. Apesar de existirem esses casos no mundo real, são tão extremos que não vale a pena mencionar. Sem contar que não existe esse perfil no dataset.

Uma variável que eu acredito que seria interessante ter no dataset é a informação de se a pessoa tem ou não filhos.

<center> <img src = "https://media.giphy.com/media/KSKvdT1YGCpUIonvSq/giphy.gif" width=500>

## Código

###   print('Olá mundo!')
"""

# Importando as bibliotecas que serão usadas
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as stats
import seaborn as sbn

"""### Algumas configurações"""

# Aumentando a quantidade de colunas exibidas pelo Pandas
pd.set_option('display.max_rows', 40)

# Removendo alguns avisos
import warnings
warnings.filterwarnings('ignore')

"""### Importando datasets, agrupando e ajustando algumas coisas"""

# Selecionando colunas de interesse nos datasets
colunas_hei = ['SEQN', 'ADHERENCE', 'HEI2015_TOTAL_SCORE']

# Importando os dados
df_demo = pd.read_csv('./data/DEMO_PHQ.csv', sep =',', encoding='UTF-8')
df_hei = pd.read_csv('./data/PAG_HEI.csv',sep =',',usecols=colunas_hei, encoding='UTF-8')

# Renomeando coluna df_hei
df_hei.rename(columns={'HEI2015_TOTAL_SCORE': "ESCORE_ALIMENTACAO"}, inplace=True)

# Combinando os dataframes utilizando a coluna SEQN
df_merge = pd.merge(df_demo, df_hei, on='SEQN')

# Removendo a coluna SEQN
df_merge.drop(columns='SEQN',axis=1,inplace=True)

# Eliminando valores nulos do dataframe combinado
df_merge = df_merge.dropna(axis=0)

# Criando lista com os índices do questionário DPQ
dpq_cols = []
for i in range(10,91,10):
    dpq_cols.append("DPQ0{}".format(i))

"""### Identificando e tratando variaveis imprecisas como "NAO SABE" ou "SE RECUSOU A RESPONDER"

#### No questionário
"""

# Contando quantas respostas 7 e 9 há no questionário
sete_nove = {}
for col in dpq_cols:
    sete = len(df_merge[df_merge[col] == 7])
    nove = len(df_merge[df_merge[col] == 9]) 
    sete_nove[col] = [sete, nove]

sete_nove

# Primeiramente, peço perdão pela gambiarra
# Segundamente, aqui eu removo linhas que possuem mais de uma resposta 9
# Terceiramente, quando eu dropei as colunas usando o índice da coluna,
# o programa alterou o tamanho do dataframe e acusou uma exceção de tamanho 
# de índice, então eu forcei a passagem.
try:
    for linha in df_merge.index:
        count = 0
        for coluna in range(9):
            if df_merge[dpq_cols].iloc[linha,coluna] == 9:
                count +=1
        if count >= 2:
            df_merge.drop(df_merge.iloc[linha].name, inplace=True)
except Exception:
    pass

# Substituindo respostas 7 e 9 no questionário por 0, para ignorar na contagem
for coluna in dpq_cols:
    df_merge[coluna] = df_merge[coluna].replace([7,9], 0)

# Somando valores do DPQ para classificação dos escores
df_merge['ESCORE_DPQ'] = df_merge[dpq_cols].sum(axis=1)

# Aplicando binning aos escores DPQ
# 0: sem sintomas; 
# 1: sintomas leves
# 2: sintomas moderados
# 3: sintomas moderadamente severos
# 4: sintomas severos
#df_merge['CLASS_DPQ'] = pd.cut(df_merge.ESCORE_DPQ, bins=[0,5,10,15,20,27], labels=[0,1,2,3,4], include_lowest=True)

df_merge['CLASS_DPQ'] = pd.cut(df_merge.ESCORE_DPQ, bins=[0,10,27], labels=[0,1], include_lowest=True)

"""#### Escolaridade"""

df_merge.DMDEDUC[df_merge.DMDEDUC >= 7].value_counts()

# Removendo linha com escolaridade imprecisa
df_merge.drop(df_merge[df_merge.DMDEDUC >= 7].index, inplace=True)

"""#### Renda"""

# Analisando os valores da variável Renda
df_merge.INDFMINC.value_counts(normalize=True).sort_index()

# Gráfico de densidade da variável Renda
sbn.displot(
    df_merge.INDFMINC,
    height=4,
    aspect=3,
    kind='kde'
)
plt.ylabel('Densidade')
plt.xlabel('Renda')

"""Achei melhor remover todos os valores imprecisos de renda"""

#Refazendo o gráfico

sbn.displot(
    df_merge.INDFMINC,
    height=4,
    aspect=3,
    kind='kde'
)
plt.ylabel('Densidade')
plt.xlabel('Renda')

# Removendo linhas com renda imprecisa
df_merge.drop(df_merge[df_merge.INDFMINC >= 12].index, inplace=True)

df_merge.INDFMINC.value_counts(normalize=False).sort_index()

"""### Análise univariada"""

colunas = ['RIAGENDR', 'RIDAGEYR', 'RIDRETH1', 'DMDEDUC', 'INDFMINC', 'ADHERENCE','ESCORE_ALIMENTACAO', 'ESCORE_DPQ']

for coluna in colunas:
    sbn.displot(
      df_merge[coluna],
        height=4,
        aspect=3,
        kind='kde')
    plt.show()

"""###  Analisando sintomas de depressão e variáveis demográficas

#### Sexo
"""

df_merge.RIAGENDR.hist()

sbn.boxplot(
    x=df_merge.RIAGENDR,
    y=df_merge.ESCORE_DPQ,
    orient='v'
)

sbn.lineplot(
    x=df_merge.RIDAGEYR,
    y=df_merge.ESCORE_DPQ,
    hue=df_merge.RIAGENDR,
    palette='tab10')

"""Note que em paticamente todas as idades, as pessoas do sexo feminino tiveram pontuações maiores do que as do sexo masculino."""

df_merge.plot(
    x='RIAGENDR',
    y='ESCORE_DPQ',
    kind='scatter'
)

plt.show()

print('Masculino\n',df_merge.ESCORE_DPQ[df_merge.RIAGENDR == 1].describe())
print()
print('Feminino\n',df_merge.ESCORE_DPQ[df_merge.RIAGENDR == 2].describe())

df_merge.RIAGENDR.groupby(df_merge.CLASS_DPQ).value_counts(normalize=1).sort_index()*100

"""Note também que pessoas do sexo feminino parecem possuir pontuações mais altas.

Testaremos melhor mais para frente

#### Idade
"""

sbn.lineplot(
    x=df_merge.RIDAGEYR,
    y=df_merge.ESCORE_DPQ,
    hue=df_merge.RIAGENDR,
    palette='tab10')

sbn.boxplot(
    data=df_merge,
    x='RIDAGEYR',
    y='CLASS_DPQ',
    orient='h'
)
plt.show()

"""Aparentemente, pessoas com idades entre 40 e 60 anos são as que mais pontuaram no questionáio DPQ"""

# Agrupando idades para comparar com as classificações do questionário DPQ
df_merge['AGE_CUT'] = pd.cut(df_merge.RIDAGEYR, bins=[18,20,30,40,50,60,70,80,84], labels=['18-19','20-29','30-39','40-49','50-59','60-69','70-79','80-84'], include_lowest=True)

df_merge.AGE_CUT.value_counts().sort_index()

# Cassifixações DPQ X Faixas de idade
sbn.lineplot(
    x=df_merge.AGE_CUT,
    y=df_merge.CLASS_DPQ,
    hue=df_merge.RIAGENDR,
    palette='tab10')

"""Analisando o gráfico acima, podemos definir a faixa etária entre 50-59 anos para ambos os sexos.

#### Etnia
"""

sbn.boxplot(
    data=df_merge,
    x='DMDEDUC',
    y='ESCORE_DPQ',
    orient='v'
)
plt.show()

df_merge.plot(
    x='RIDRETH1',
    y='ESCORE_DPQ',
    kind='scatter'
)

sbn.lineplot(
    x=df_merge.AGE_CUT,
    y=df_merge.CLASS_DPQ,
    hue=df_merge.RIDRETH1,
    palette='tab10')

# Sexo Masculino
sbn.lineplot(
    x=df_merge.RIDRETH1,
    y=df_merge.CLASS_DPQ,
    hue=df_merge.RIAGENDR,
    palette='tab10')
plt.show()

"""O sexo feminino aponta para 'negro não-hispânico'.

Já o sexo masculino, aponta para 'negro não-hispânico' e 'outro hispânico'.

#### Escolaridade
"""

# Escolaridade
sbn.boxplot(
    data=df_merge,
    x='DMDEDUC',
    y='ESCORE_DPQ',
    orient='v'
)
plt.show()

sbn.lineplot(
    x=df_merge.DMDEDUC,
    y=df_merge.ESCORE_DPQ,
    hue=df_merge.RIAGENDR,
    palette='tab10')

"""O gráfico nos mostra que quanto menor o grau de escolaridade, maior a pontuação no questionário DPQ.

O gráfico também aponta que homens e mulheres, para um mesmo grau de escolaridade, possuem diferenças bastante significativas no questionário DPQ

#### Renda
"""

# Renda
sbn.boxplot(
    data=df_merge,
    x='INDFMINC',
    y='CLASS_DPQ',
    orient='h'
)
plt.show()

sbn.lineplot(
    x=df_merge.INDFMINC,
    y=df_merge.CLASS_DPQ,
    hue=df_merge.RIAGENDR,
    palette='tab10')

"""Ambos os sexos convergem para renda entre 5000-9999 dólares

#### Conclusão

Com base na análise bivariada entre variáveis demográficas e o resultado do questionário DPQ. Foi possível elaborar um perfil com maior incidência de sintomas de depressão: (i) sexo feminino, (ii) entre 50 e 59 anos, (iii) negra não-hispânica, (iv) que estudou até o 12° ano e (v) que possui renda entre 5000 e 9999 dólares.

### Analisando hábitos saudáveis e características demográficas

#### Alimentação
"""

df_merge.ESCORE_ALIMENTACAO.describe()

"""##### Alimentação x Sexo"""

sbn.boxplot(
    data=df_merge,
    x='RIAGENDR',
    y='ESCORE_ALIMENTACAO',
    orient='v'
)
plt.show()

df_merge.ESCORE_ALIMENTACAO.groupby(df_merge.RIAGENDR).describe()

"""##### Alimentação x Idade"""

sbn.lineplot(
    x=df_merge.RIDAGEYR,
    y=df_merge.ESCORE_ALIMENTACAO,
    palette='tab10'
)
plt.show()

sbn.lineplot(
    x=df_merge.RIDAGEYR,
    y=df_merge.ESCORE_ALIMENTACAO,
    hue=df_merge.RIAGENDR,
    palette='tab10'
)
plt.show()

sbn.lineplot(
    x=df_merge.AGE_CUT,
    y=df_merge.ESCORE_ALIMENTACAO,
    palette='tab10'
)
plt.show()

sbn.lineplot(
    x=df_merge.AGE_CUT,
    y=df_merge.ESCORE_ALIMENTACAO,
    hue=df_merge.RIAGENDR,
    palette='tab10'
)
plt.show()

sbn.boxplot(
    x=df_merge.AGE_CUT,
    y=df_merge.ESCORE_ALIMENTACAO,
    orient='v',
    palette='tab10'
)
plt.show()

df_merge.ESCORE_ALIMENTACAO.groupby([df_merge.AGE_CUT, df_merge.RIAGENDR]).mean().sort_index()

"""##### Alimentação x Renda"""

sbn.boxplot(
    data=df_merge,
    x='INDFMINC',
    y='ESCORE_ALIMENTACAO',
    orient='v'
)
plt.show()

# Separando por sexo
sbn.boxplot(
    data=df_merge,
    x='INDFMINC',
    y='ESCORE_ALIMENTACAO',
    hue='RIAGENDR',
    orient='v'
)
plt.show()

sbn.lineplot(
    x=df_merge.INDFMINC,
    y=df_merge.ESCORE_ALIMENTACAO,
    palette='tab10'
)
plt.show()

# Separando por sexo
sbn.lineplot(
    x=df_merge.INDFMINC,
    y=df_merge.ESCORE_ALIMENTACAO,
    hue=df_merge.RIAGENDR,
    palette='tab10'
)
plt.show()

"""##### Alimentação x Etnia"""

sbn.lineplot(
    x=df_merge.RIDRETH1,
    y=df_merge.ESCORE_ALIMENTACAO,
    palette='tab10')

sbn.lineplot(
    x=df_merge.RIDRETH1,
    y=df_merge.ESCORE_ALIMENTACAO,
    hue=df_merge.RIAGENDR,
    palette='tab10')

"""##### Alimentação x Escolaridade"""

sbn.boxplot(
    data=df_merge,
    x='DMDEDUC',
    y='ESCORE_ALIMENTACAO',
    orient='v'
)
plt.show()

sbn.lineplot(
    x=df_merge.DMDEDUC,
    y=df_merge.ESCORE_ALIMENTACAO,
    hue=df_merge.RIAGENDR,
    palette='tab10')

"""##### Conclusão alimentação

O perfil que possui maior adequação a uma alimentação saudável é o de uma pessoa do sexo feminino, branca, com mais de 70 anos, com renda entre US$45000 e US$54999 anuais ou maior que US$75000, e que estudou até o 9 ano ou possui ensino superior completo.

#### Atividade Fisica

##### Atividade Fisica x Sexo
"""

df_merge.ADHERENCE.groupby(df_merge.RIAGENDR).describe()

df_merge.ADHERENCE.groupby(df_merge.RIAGENDR).value_counts(normalize=1).sort_index()

df_merge.ADHERENCE.groupby(df_merge.RIAGENDR).describe()

sbn.lineplot(
    data=df_merge,
    x='RIAGENDR',
    y='ADHERENCE',
)
plt.show()

"""##### Atividade Fisica x Idade"""

df_merge.ADHERENCE.groupby(df_merge.AGE_CUT).describe().sort_index()

sbn.lineplot(
    y=df_merge.ADHERENCE,
    x=df_merge.AGE_CUT,
    hue=df_merge.RIAGENDR,
    palette='tab10'
)

"""##### Atividade Fisica x Renda"""

df_merge.ADHERENCE.groupby(df_merge.INDFMINC).describe().sort_index()

df_merge.ADHERENCE.groupby(df_merge.INDFMINC).describe().sort_values('mean').tail(4)

sbn.lineplot(
    y=df_merge.ADHERENCE,
    x=df_merge.INDFMINC,
    palette='tab10'
)

sbn.lineplot(
    y=df_merge.ADHERENCE,
    x=df_merge.INDFMINC,
    hue=df_merge.RIAGENDR,
    palette='tab10'
)

"""##### Atividade Fisica x Etnia"""

df_merge.ADHERENCE.groupby(df_merge.RIDRETH1).describe()

df_merge.ADHERENCE.groupby(df_merge.RIDRETH1).value_counts(normalize=1).sort_index()

df_merge.RIDRETH1.groupby(df_merge.ADHERENCE).value_counts(normalize=1).sort_index()

sbn.boxplot(
    x=df_merge.ADHERENCE,
    y=df_merge.RIDRETH1,
    orient='v'
)

sbn.lineplot(
    y=df_merge.ADHERENCE,
    x=df_merge.RIDRETH1,
    hue=df_merge.RIAGENDR,
    palette='tab10')

"""##### Atividade Fisica x Escolaridade"""

df_merge.ADHERENCE.groupby(df_merge.DMDEDUC).describe()

df_merge.ADHERENCE.groupby([df_merge.AGE_CUT, df_merge.DMDEDUC]).describe().sort_index()

sbn.lineplot(
    x=df_merge.DMDEDUC,
    y=df_merge.ADHERENCE,
    hue=df_merge.RIAGENDR,
    palette='tab10'
)
plt.show()

"""##### Conclusão Atividade física
 
 O perfil com maior aderência à atividades físicas é o de uma pessoa do sexo masculino, negra ou 'outra-hispânica', entre 18 e 19 anos com renda de até US$4999 anuais ou renda maior que 75000.

### Analisando sintomas de depressão e hábitos saudáveis
"""

df_merge.ESCORE_DPQ.groupby(df_merge.ADHERENCE).describe()

sbn.lineplot(
    x=df_merge.ADHERENCE,
    y=df_merge.ESCORE_DPQ,
    palette='tab10'
)

sbn.lineplot(
    x=df_merge.ADHERENCE,
    y=df_merge.ESCORE_DPQ,
    hue=df_merge.RIAGENDR,
    palette='tab10'
)

df_merge.ESCORE_ALIMENTACAO.groupby(df_merge.CLASS_DPQ).describe()

sbn.boxplot(
    x=df_merge.CLASS_DPQ,
    y=df_merge.ESCORE_ALIMENTACAO,
    orient='v'
)

sbn.lineplot(
    x=df_merge.CLASS_DPQ,
    y=df_merge.ESCORE_ALIMENTACAO,
    palette='tab10'

)

sbn.lineplot(
    x=df_merge.CLASS_DPQ,
    y=df_merge.ESCORE_ALIMENTACAO,
    hue=df_merge.RIAGENDR,
    palette='tab10'

)

"""#### Conclusão sintomas de depressão x Habitos Saudáveis

Há correlação entre aderência e a pontuação no questionário DPQ. Também existe correlação entre a alimentação e a pontuação no questionário DPQ.

### Testes de hipótese etc.

Não consegui pensar numa forma de aplicar algum teste de hipóteses que coubesse aqui. Então prossegui utilizando apenas uma matriz de correlação e um heatmap.
"""

df_final = df_merge[['RIAGENDR', 'RIDAGEYR', 'RIDRETH1', 'DMDEDUC','INDFMINC', 'ADHERENCE', 'ESCORE_ALIMENTACAO', 'ESCORE_DPQ']]

df_final.head()

sbn.set_context(font_scale=1.9)
plt.figure(figsize=(12,8))

sbn.heatmap(
    df_final.corr(), 
    annot=True,
    fmt='.2f', 
    cmap='plasma_r', 
    mask=np.triu(np.ones_like(df_final.corr()))
)

plt.show()